# Generated by Django 4.2.3 on 2023-07-21 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='asset_traking.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='asset_traking.company')),
            ],
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_quantity', models.SmallIntegerField(default=1)),
                ('checkout_time', models.DateTimeField()),
                ('checkout_condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10)),
                ('chekout_note', models.TextField(max_length=1000)),
                ('duration', models.DateField()),
                ('is_returned', models.BooleanField(default=False)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('return_quantity', models.SmallIntegerField(default=1)),
                ('return_condition', models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged'), ('lost', 'Lost')], max_length=10, null=True)),
                ('returned_note', models.TextField(max_length=1000)),
                ('issuing_time', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='asset_traking.asset')),
                ('checkout_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_checkout_staff', to='asset_traking.staff')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_companys', to='asset_traking.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_employee', to='asset_traking.employee')),
                ('returned_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_returned_staff', to='asset_traking.staff')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset_traking.company'),
        ),
    ]
