# Generated by Django 4.2.3 on 2023-07-21 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_traking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlog',
            name='checkout_by_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_staff_logs', to='asset_traking.staff'),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_logs_company', to='asset_traking.company'),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_logs_employee', to='asset_traking.employee'),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='returned_by_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_staff_logs', to='asset_traking.staff'),
        ),
    ]
