# Generated by Django 4.2.3 on 2023-07-21 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_traking', '0003_rename_name_staff_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='adress',
            new_name='address',
        ),
    ]
