# Generated by Django 4.2.3 on 2023-07-21 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_traking', '0004_rename_adress_staff_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlog',
            name='chekout_note',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='return_quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='returned_by_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_staff_logs', to='asset_traking.staff'),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='returned_note',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
